### ISSUE TITLE
Stuck on spinner after pay button is clicked

### ISSUE THREAD

**Issue by hommyshop** [wirecard/shopify-ee#11] opened 2019-07-28 18:05 UTC
UPDATE: Found the bug with 100% reproduction.

It happens on Chrome autofill. Chrome enters the date in format 01/2023, while the form's validator only accepts the format 01/23. The form does not validate, there is no error and the customer is unable to complete the payment.

This week many customers keep reporting that they are stuck on the spinner at the final payment page. They enter their card details, click the payment button and nothing happens. There is also no payment attempts (failed or successful) in WEP.

Some are saying the spinner only happens for a split second and nothing else happens.

So far we cannot replicate the issue, however it is clearly something is wrong due to the number of reports we keep receiving.

Here are screenshots of the emails we received so far:

1 request:
![image](https://user-images.githubusercontent.com/49198848/62010978-e786ac00-b17a-11e9-8b93-2e443a189d3b.png)

![image](https://user-images.githubusercontent.com/49198848/62010982-fc633f80-b17a-11e9-8a34-d290ae15ca68.png)

2 request:

![image](https://user-images.githubusercontent.com/49198848/62011008-5106ba80-b17b-11e9-839c-839cc8667bc0.png)

3 request:

![image](https://user-images.githubusercontent.com/49198848/62011019-6d0a5c00-b17b-11e9-9ade-0379205f87bc.png)

![image](https://user-images.githubusercontent.com/49198848/62012453-20c91700-b18f-11e9-8233-4589c9f15f3c.png)

**Comment by hommyshop** [comment] 2019-08-01 09:20
Another customer reported and hinted that the problem is related to Autofill.

It makes sense, as the spinner appearing for a split second is identical to the one clicking on the payment button and the form failing to validate. All of the customers claim they were able to enter their credit card details, however the payment button does not do anything. It means the form fails to validate, and also in WEP there is no failed attempt of payment. Only a form visit is recorded and no payment attempts appear.

The customer says that they used a Huawei mobile phone - so likely Chrome web browser. I believe the issue could be somehow related to Chrome's autofill. Both mobile and desktop seem to be affected. We still cannot reproduce the bug. Maybe it is only in some chrome versions or some other circumstances.

Please try to identify the issue as it is affecting a significant percentage of our customers.

**Comment by hommyshop** [comment] 2019-08-01 19:19
UPDATE:

I noticed the autofill on Chrome does not pick up cardholder name.

Could be related to the issue as last name is a required field.

**Comment by hommyshop** [comment] 2019-08-01 19:41
UPDATE: Found the bug with 100% reproduction.

It happens on Chrome autofill. Chrome enters the date in format 01/2023, while the form's validator only accepts the format 01/23. The form does not validate, there is no error and the customer is unable to complete the payment.

**Comment by paolodellucci** [comment] 2019-08-02 10:19
We are also having this exact issue. Multiple customers have been reporting this problem for weeks now. Please fix it asap.

**Comment by hommyshop** [comment] 2019-08-02 11:46
can we get this fixed today? every day we get tons of customers sending us these emails:

![image](https://user-images.githubusercontent.com/49198848/62368091-3eea9a80-b534-11e9-8bb9-65217670cefd.png)



we already reproduced the bug and documented, please just spend a little time and fix this. This bug did not exist before and was introduced during one of the updates.

**Comment by hommyshop** [comment] 2019-08-05 13:07
Can we get a basic client side hotfix that would replace the autofill value to the supported value?

It was already being replaced before and was recently broken.

We don't need you guys to update the whole system to support the other date format.

We just want a quick hotfix to replace the input to the right value with a basic Javascript on the client side.

**Comment by hommyshop** [comment] 2019-08-09 08:06
The problem still exists on the latest chrome version. Every chrome user on desktop and mobile are affected. Here's a video to show it again:

[https://www.youtube.com/watch?v=3pZ7z1JIxKg](url)

**Comment by jakubpolomsky** [comment] 2019-11-12 09:28
Hello, we did several updates in the last few weeks and were unable to reproduce any of the errors after that. I will close the issue now as the problems will not occur anymore. The autofilled data is now parsed correctly.

Kind regards

**Closed by jakubpolomsky** 2019-11-12 09:28 UTC
